# packages in environment at /Users/ronald/anaconda3/envs/amznas:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl  
ca-certificates           2021.1.19            hecd8cb5_1  
certifi                   2020.12.5        py39hecd8cb5_0  
click                     7.1.2              pyhd3eb1b0_0  
intel-openmp              2019.4                      233  
libcxx                    10.0.0                        1  
libffi                    3.3                  hb1e8313_2  
mkl                       2019.4                      233  
mkl-service               2.3.0            py39h9ed2024_0  
mkl_fft                   1.3.0            py39ha059aab_0  
mkl_random                1.0.2            py39h16bde0e_0  
ncurses                   6.2                  h0a44026_1  
numpy                     1.19.2           py39he57783f_0  
numpy-base                1.19.2           py39hde55871_0  
openssl                   1.1.1j               h9ed2024_0  
pandas                    1.2.3            py39hb2f4e1b_0  
phonlab                   0.0.0                    pypi_0    pypi
pip                       21.0.1           py39hecd8cb5_0  
python                    3.9.2                h88f2d9e_0  
python-dateutil           2.8.1              pyhd3eb1b0_0  
pytz                      2021.1             pyhd3eb1b0_0  
pyyaml                    5.4.1            py39h9ed2024_1  
readline                  8.1                  h9ed2024_0  
setuptools                52.0.0           py39hecd8cb5_0  
six                       1.15.0           py39hecd8cb5_0  
sqlite                    3.35.2               hce871da_0  
tk                        8.6.10               hb0a8c7a_0  
tzdata                    2020f                h52ac0ba_0  
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h1de35cc_0  
yaml                      0.2.5                haf1e3a3_0  
zlib                      1.2.11               h1de35cc_3  
